export const obat = [
  {
    id: "obat-01",
    nama_obat: "Obat kuat",
    jenis_obat: "non resep",
    tanggal_expired: "2024-05-22",
    jumlah: 0,
    harga_beli: 125000,
    harga_jual: 150000,
    stok_obat: 15,
    kategori_obat: "dewasa ",
    sub_kategori: "untuk hubungan dewasa",
    id_staff: "staff-01",
    id_supplier: "supplier-01",
    tipe_obat: "pil",
    gambar: "https://cf.shopee.co.id/file/d4e8284aa963e4f05895485a73e7153b",
  },
  {
    id: "obat-02",
    nama_obat: "Obat tidur",
    jenis_obat: "non resep",
    tanggal_expired: "2024-07-30",
    jumlah: 0,
    harga_beli: 175000,
    harga_jual: 220000,
    stok_obat: 27,
    kategori_obat: "di atas 3 tahun",
    sub_kategori: "untuk tidur",
    id_staff: "staff-02",
    id_supplier: "supplier-01",
    tipe_obat: "pil",
    gambar: "https://storage.googleapis.com/rxstorage/Product/large/Apotek_Online_Farmaku.com_Lelap_Strip.jpg",
  },
  {
    id: "obat-03",
    nama_obat: "Obat Flu",
    jenis_obat: "resep",
    tanggal_expired: "2023-12-15",
    jumlah: 0,
    harga_beli: 80000,
    harga_jual: 100000,
    stok_obat: 20,
    kategori_obat: "umum",
    sub_kategori: "penyakit ringan",
    id_staff: "staff-02",
    id_supplier: "supplier-02",
    tipe_obat: "tablet",
    gambar: "https://example.com/obat-flu.jpg",
  },
  {
    id: "obat-04",
    nama_obat: "Obat Batuk",
    jenis_obat: "non resep",
    tanggal_expired: "2024-08-10",
    jumlah: 0,
    harga_beli: 55000,
    harga_jual: 70000,
    stok_obat: 30,
    kategori_obat: "umum",
    sub_kategori: "penyakit ringan",
    id_staff: "staff-03",
    id_supplier: "supplier-01",
    tipe_obat: "sirup",
    gambar: "https://example.com/obat-batuk.jpg",
  },
  {
    id: "obat-05",
    nama_obat: "Vitamin C",
    jenis_obat: "non resep",
    tanggal_expired: "2023-11-30",
    jumlah: 0,
    harga_beli: 30000,
    harga_jual: 40000,
    stok_obat: 25,
    kategori_obat: "suplemen",
    sub_kategori: "vitamin",
    id_staff: "staff-01",
    id_supplier: "supplier-02",
    tipe_obat: "tablet",
    gambar: "https://example.com/vitamin-c.jpg",
  },
  {
    id: "obat-06",
    nama_obat: "Paracetamol",
    jenis_obat: "Tablet",
    tanggal_expired: "2023-12-31",
    jumlah: 100,
    harga_beli: 5000,
    harga_jual: 7000,
    stok_obat: 80,
    kategori_obat: "Analgesik",
    sub_kategori: "Obat Bebas",
    id_staff: "staff-01",
    id_supplier: "supplier-02",
    tipe_obat: "taplet",
    gambar: "https://example.com/paracetamol.jpg",
  },
  {
    id: "A002",
    nama_obat: "Amoxicillin",
    jenis_obat: "Kapsul",
    tanggal_expired: "2024-06-30",
    jumlah: 50,
    harga_beli: 8000,
    harga_jual: 12000,
    stok_obat: 45,
    kategori_obat: "Antibiotik",
    sub_kategori: "Resep Dokter",
    id_staff: "ST002",
    id_supplier: "SUP002",
    tipe_obat: "Generik",
    gambar: "amoxicillin.jpg",
  },
];
